### ISSUE TITLE
Client crashes on attempt to render Experience Events related to Localized Resources

### ISSUE THREAD

**Issue by wowgain** [Cediner/ArdClient#4]
[Haven Exception 2020.11.18.01.36.34.log](https://github.com/Cediner/ArdClient/files/5560224/Haven.Exception.2020.11.18.01.36.34.log)
[Haven Exception 2020.11.18.02.18.20.log](https://github.com/Cediner/ArdClient/files/5560225/Haven.Exception.2020.11.18.02.18.20.log)

**Comment by Cediner** [comment]
little information and a possible fix is ​​already there
