### ISSUE TITLE
Change UI size?

### ISSUE THREAD

**Issue by se7enek** [Cediner/ArdClient#40]
Either missing feature or im totally blind (yeah thats the reason why i need bigger UI :P)

**Comment by Cediner** [comment]
![image](https://user-images.githubusercontent.com/10575378/113607080-7ab2fd00-9651-11eb-94d7-f991f8e836d9.png)

**Comment by se7enek** [comment]
Available yet not included, means i can include it myself somehow? Or maybe i can edit some config setting? Anything (far from perfect) would be fine for me as im blind as rat ;D
