### ISSUE TITLE
U can't hide frogs

### ISSUE THREAD

**Issue by UnManism** [Cediner/ArdClient#43]
In minimap in icon setting, even if i have unchecked to show frogs they still are showing on minimap.

**Comment by Cediner** [comment]
Shift + M. Right column.

**Comment by UnManism** [comment]
U are fast mate :D
So for what purpose is having icon settings if they dont work propertly? Or that is a line of code that was to dumb writen to bother?

**Comment by Cediner** [comment]
This is an old client who barely lives, much works much as it should have some crutches.
I don't make sense to engage in small corrections, I do a new client.

**Comment by UnManism** [comment]
Thats what i was thinkig. Great job
