### ISSUE TITLE
Can't reach HavenPanel.lui through PBot scripts

### ISSUE THREAD

**Issue by leksar** [Cediner/ArdClient#44]
```js
const HavenPanel = Java.type("haven.HavenPanel");
const hRootWidget = HavenPanel.lui.root;
```

it was possible in old client, but now HavenPanel.lui returns undefined

**Comment by Cediner** [comment]
const root = Java.type('haven.purus.pbot.PBotAPI').ui().root;
look at official scripts in the scripts/official folder

**Comment by leksar** [comment]
works well i guess, thank you
