### ISSUE TITLE
PBotCheckbox is using the wrong base constructor.

### ISSUE THREAD

**Issue by Djekke** [Cediner/ArdClient#45]
https://github.com/Cediner/ArdClient/blob/d64ee32a4f9d2a3c37efe81d0b449cbe9424bf17/src/haven/purus/pbot/gui/PBotCheckbox.java#L10-L12

val is supposed to be the initial value (I guess), but in base constructor it's the size of checkbox

https://github.com/Cediner/ArdClient/blob/00bb3a6bf988e6d70dccea5fd37c253686685488/src/haven/CheckBox.java#L51-L65

**Comment by Cediner** [comment]
ok
