### ISSUE TITLE
findObjectsByNames in PBotGobAPI not returning full list

### ISSUE THREAD

**Issue by Djekke** [Cediner/ArdClient#47]
Remnants of code from `findObjectByNames` method (that returns single nearest gob) are leading to missing gobs.

Just delete this lines:
https://github.com/Cediner/ArdClient/blob/d64ee32a4f9d2a3c37efe81d0b449cbe9424bf17/src/haven/purus/pbot/PBotGobAPI.java#L163
https://github.com/Cediner/ArdClient/blob/d64ee32a4f9d2a3c37efe81d0b449cbe9424bf17/src/haven/purus/pbot/PBotGobAPI.java#L198
https://github.com/Cediner/ArdClient/blob/d64ee32a4f9d2a3c37efe81d0b449cbe9424bf17/src/haven/purus/pbot/PBotGobAPI.java#L231

**Comment by Cediner** [comment]
ok
