### ISSUE TITLE
PBot multithreading not wotking

### ISSUE THREAD

**Issue by Djekke** [Cediner/ArdClient#48]
Creating a new thread for PBotButton and PBotCheckbox throws an error. **(And for PBotCheckbox, this causes the client to crash as there is no try..catch block)**
`java.lang.IllegalStateException: Multi threaded access requested by thread Thread[Thread-25,5,Haven client] but is not allowed for language(s) js.`

As far as I researched that error: concurrent access to JavaScript objects is not allowed: any JavaScript object cannot be accessed by more than one thread at a time. (https://www.graalvm.org/reference-manual/js/Multithreading/)

**Comment by Cediner** [comment]
I looked today. I think it is better to stay without it. I will later make the engine of scripts and I will understand more. try just put ; аfter the function. I do not have problems with scripts. Look at the Butcher script in the folder with scripts.
