### ISSUE TITLE
Session Multi-Client Feature memory leak

### ISSUE THREAD

**Issue by wowgain** [Cediner/ArdClient#50]
Using the Sessions multi-client feature seems to invariably lead to issues with memory leaks consistently, particularly when creating and logging into a new session where one character is inside of another instanced area (such as a building, in a cave, etc) while the other is outside in the overworld. Can't exactly list any error logs with this since it doesn't lead to crashes, but at this point the game becomes more or less unplayable due to constant buffering framerates (jumps from playable to about 3 or 4 before getting back to regular framerates) every few seconds. Only way to fix the problem at this point is just to launch a new instance of the client and log back in again.

**Comment by wowgain** [comment]
Nix that, just got a crash for the first time from it as I wrote this up lol

2021.08.20.8acc63d4
Windows 10 10.0 x64, 1.8.0_271 amd64
NVIDIA Corporation (NVIDIA GeForce MX150/PCIe/SSE2) - 4.6.0 NVIDIA 471.41

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at haven.Session$RWorker.run(Session.java:443)

**Comment by Cediner** [comment]
I do not know how to repair it and where the source of the problem
I can offer to use any launch arguments: https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html
