### ISSUE TITLE
Is PBot scripting moving towards Python or will JS still be supported? 

### ISSUE THREAD

**Issue by mitchkm** [Cediner/ArdClient#51]
Just curious as I started to build out some JS bot scripts as the Python ones seem to be non-functional atm. Also, anyone else script? Is there a shared repository of scripts people work on to share knowledge? Would be interested in contributing as well.

**Comment by Cediner** [comment]
Scripting for Python was written spontaneously, so see scripts/py/test.py
In essence, it is the same JS script only on python
The whole system is already outdated, and old scripts that shared look differently.
Scripts can be viewed in scripts/official, and the code for them is Java code from the client.

**Comment by mitchkm** [comment]
Ah, so JS scripting is still the official and here to stay? Are there a generated Javadocs?

**Comment by Cediner** [comment]
Official is the name of the folder. These are not private scripts, but public who work and updated by me.
For your personal, you can make another folder and call it as you want, or you can not create.
Python was added as an alternative, and should work simultaneously and in parallel with JS.
I did not test a lot, but Python should work fine, like JS.

**Comment by Cediner** [comment]
See code

https://github.com/Cediner/ArdClient/tree/Unstable/src/haven/purus/pbot
some methods

**Comment by mitchkm** [comment]
Much appreciated for the quick response! Looking forward to continuing my bot scripting in JS :) and using your amazing client!

I don't suppose there is a discord for the client/bot-scripting?

**Comment by Cediner** [comment]
This client is collected from different others.
For example, Script-Module is Purus Pasta. But a little mutated.
The discord was, but it was closed. I just support life while there are those who use this client. But because of the different circumstances, it's not long to live, and it is not particularly necessary.

**Comment by mitchkm** [comment]
Oh this client is reaching end of life! What client makes it obsolete?

**Comment by Cediner** [comment]
Vanilla (new render) (check changelogs), this is Quasimodo from 1,000,000 different clients, and desire to make the best and right client

**Comment by mitchkm** [comment]
Ah so is it just Ender and Purus Pasta actively updating to the vanilla new render client?
