### ISSUE TITLE
"Cannot create food info: oname" for smoked food

### ISSUE THREAD

**Issue by VGukalov** [Cediner/ArdClient#60]
I made different smoked sausages with Golden chain tree (no one on food service still).
Started client with console window.
When my smoked sausages are in view, client outputs error in console "Cannot create food info: oname" instead of sending data.

**Comment by Cediner** [comment]
Fixed [84203cd](https://github.com/Cediner/ArdClient/commit/84203cd5e58e15231fd672842b62c0005667ed58)
