### ISSUE TITLE
Unclear behavior with smoked meat cuts & fish

### ISSUE THREAD

**Issue by VGukalov** [Cediner/ArdClient#61]
1. Given 0 entries with desired smoked food in database https://food.hearthlands.net/ 
   (for ex. name:Smoked plaice;from:olive)
2. Smoked plaice with olive tree has been made, taken and placed in cupboard.
3. Client sends nothing.
4. No entries added to database.

Same happened with other 15 fish cuts smoked with olive tree
And probably with raw meat too.
But sausages work well!

**Comment by Cediner** [comment]
Fixed: [4e21fb5](https://github.com/Cediner/ArdClient/commit/4e21fb57457bb0003817471eea4f9005dad9ee9f)
(maybe)

**Comment by VGukalov** [comment]
> Fixed: [4e21fb5](https://github.com/Cediner/ArdClient/commit/4e21fb57457bb0003817471eea4f9005dad9ee9f) (maybe)

It works some way. Recipes for smoked meat and fish added to database.
But their names start with "Smoked smoked [meat]" and have incorrect icon.
for ex.: name:smoked plaice;from:olive

**Comment by Cediner** [comment]
Fixed: [779b4db](https://github.com/Cediner/ArdClient/commit/779b4dbec54fb13f27ca15de89f5c23a6a159da6)
