### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by LaurynasZuk** [Cediner/ArdClient#62]
1. Minimap don't have cliff outline anymore. 
2. This kinda mess.
![037c41778e72203c486a6283dd454784](https://user-images.githubusercontent.com/116870769/198527809-b186b663-c401-4686-a4cb-06958842982e.png)

**Comment by Cediner** [comment]
Fixed: [e1e2ee7](https://github.com/Cediner/ArdClient/commit/e1e2ee73b2df849d42fd0a80b6906f2aed335fbb)
