### ISSUE TITLE
Flickering.

### ISSUE THREAD

**Issue by LaurynasZuk** [Cediner/ArdClient#63]
When mining, screen started to flicker, like it reloads screen or something like that.

**Comment by Cediner** [comment]
[e1e2ee7](https://github.com/Cediner/ArdClient/commit/e1e2ee73b2df849d42fd0a80b6906f2aed335fbb) ??? check?

**Comment by LaurynasZuk** [comment]
It causes flickering sometimes, reloaded and fixed, but still, sometimes client not loading all objects, after reload it fixes.

**Comment by LaurynasZuk** [comment]
Feels like okey now.

**Comment by Cediner** [comment]
I will fix something else
