### ISSUE TITLE
"Farmer" bot throws an error on placing stage

### ISSUE THREAD

**Issue by AndreiRomaniuk** [Cediner/ArdClient#66]
**Describe the bug**
Farmer bot "SeedCropFarmer.java" have an error on the stage of placing piles

**To Reproduce**
1. Use script "Farmer" from automation
2. Wait till script start placing
3. See error

**Expected behavior**
Piles should be placed right

**Screenshots**
```2022.11.12.f611ae4c
Windows 10 10.0 x64, 1.8.0_341 amd64
NVIDIA Corporation (NVIDIA GeForce GTX 1650/PCIe/SSE2) - 4.6.0 NVIDIA 512.15

java.lang.NoSuchFieldError: placing
	at haven.purus.pbot.PBotGobAPI.placeThing(PBotGobAPI.java:555)
	at haven.purus.SeedCropFarmer.run(SeedCropFarmer.java:846)
	at java.lang.Thread.run(Unknown Source)
```
Java 8 341

**Additional context**
Searched in repository, MapView.java file says that placing var exists in that map class

**Comment by Cediner** [comment]
[3d1dffb](https://github.com/Cediner/ArdClient/commit/3d1dffbbfb997078d6beb8c6378bb85308b9478a)

**Comment by AndreiRomaniuk** [comment]
Thanks, already tested on straw piles, it works
