### ISSUE TITLE
Object inventory

### ISSUE THREAD

**Issue by LaurynasZuk** [Cediner/ArdClient#69]
Can you make option, that shows an free/full(who got content inside) wheelbarrows, chest and other stuff who got inventory, to show in wagons, knars, snekjas. To make colors like green/red.
![1ec0619b323e31d781f14e273e3befa2](https://user-images.githubusercontent.com/116870769/205927004-e1a34f57-3bb6-40d5-b99f-968433c41250.png)

**Comment by Cediner** [comment]
No, this is static image without any information.
