### ISSUE TITLE
SeedCropFarmer.java: big piles stockpiling bug

### ISSUE THREAD

**Issue by AndreiRomaniuk** [Cediner/ArdClient#74]
**Describe the bug**
Straw piles are big, the size of pile is more than 1 tile. So before, when you was using "stockpile" checkbar in cropfarmer, piles was created every 2 tiles, like this:
![Screenshot_4](https://user-images.githubusercontent.com/7248451/221405856-396ef51a-08c5-4e84-9e25-f2b332390ba3.png)
Steps was like this:
1 Place first pile on first tile
2 Move and check second tile
3 Second tile is occupied(by a pile on first tile)
4 Move and check third tile
5 Tile is empty, place pile
and then repeat untill stock area ends
But now steps like that:
1 Place first pile on first tile
2 Move and check second tile
3 Second tile is occupied(by a pile on first tile)
4 Farmer finished work
It is placing one pile and even not filling it with straw from inventory, just break the cycle.
![Screenshot_3](https://user-images.githubusercontent.com/7248451/221406179-23b85e27-b237-4ddc-b0fc-d85ddb9a8710.png)

**To Reproduce**
1 Take at least 2 straw items and 1 empty barrel
2 Run farmer, check "stockpile" checkbox
3 Select random empty "selec area" and 1x3 empty "stockpile area" zones
4 Press any straw crop button, barley for example, alt-click on empty barrel
5 Press that straw crop button again and wait untill the bug

**Comment by Cediner** [comment]
idk, it work for me
https://discord.gg/24Tq35uwBD - discord (having ard channel)
