### ISSUE TITLE
l10n update and messages in console

### ISSUE THREAD

**Issue by Nibe1ung** [Cediner/ArdClient#75]
Hello Cediner.
I have a few questions.
1. Do you plan update l10n files? Some parameters are missed. There aren't for skills: Landscaping, Ancestral Worship, Charcoal Burning, Glass Blowing. I found for 1 and 2 - paginae/skills/ancw and paginae/skills/landscaping . I have no idea what should be for other two. Also, doesn't match parameters for Action Menu.
2. When client starts throw console there are these messages:
Wrong res version (24 != 25) gfx/borka/body(v25)
Wrong res version (13 != 15) gfx/borka/idle(v15)
Wrong res version (20 != 24) gfx/borka/male(v24)
Wrong res version (3 != 4) gfx/hud/chr/fev/con(v4)
Wrong res version (3 != 5) gfx/hud/chr/fev/dex(v5)
Wrong res version (3 != 5) gfx/hud/chr/fev/int(v5)
Wrong res version (3 != 5) gfx/hud/chr/fev/prc(v5)
Wrong res version (1 != 2) gfx/invobjs/bucket(v2)
Wrong res version (14 != 15) sfx/tiles/step(v15)
Wrong res version (6 != 7) gfx/terobjs/herbs/blueberry(v7)
Wrong res version (77 != 80) gfx/terobjs/pow(v80)
Wrong res version (15 != 20) gfx/terobjs/trees/pine(v20)
Wrong res version (8 != 9) lib/plants(v9) ......
and many other.
Seems some res files needs update too, isn't it?

I will be glad to help but I don't know how.

Thank you for your future response.
WBR

**Comment by Cediner** [comment]
No, this client will continue to be "on a drip" as long as the developers allow the "old render" to live.
I will not evolve this client. It will die.
