### ISSUE TITLE
Bill of possession pole visibility.

### ISSUE THREAD

**Issue by ghost** [Cediner/ArdClient#92]
The pole that appears after a movable item is marked with BoP isn't present in Ard. The default client works as intended.
Ard:
![image_2023-11-27_022551889](https://github.com/Cediner/ArdClient/assets/25268166/f22e2a87-0c12-4b78-a9c3-3a98fed40276)
Default:
![image](https://github.com/Cediner/ArdClient/assets/25268166/e159bdd9-e42e-4b68-ba98-3875e5d6755c)

Makes it impossible for the buyer to see which BoP is tied to which object (should highlight red on mouseover, as visible in the picture) and makes it impossible to remove a BoP from an item.

**Comment by Cediner** [comment]
https://github.com/Cediner/ArdClient/commit/ebc192c589bd4cdf43c12c2b764e624dc7f8cc2e

**Comment by ghost** [comment]
Fix is bugged, continuing:
Mouseover onto the ownership part of BoP (which has been named and is located in your inventory) blacks out the screen excluding the interface, and bugs out your avatar in the top-left. Taking the cursor off the BoP returns the game to a normal state.

Errors from debug included:
![image](https://github.com/Cediner/ArdClient/assets/25268166/821ad5e5-87ef-4772-aad2-0d0305aa813b)

**Comment by ghost** [comment]
Addition: red highlight is not present on BoP mouseover when it is located inside a trading stand, but the screen and game state seems to be normal otherwise.

Ard:
![image](https://github.com/Cediner/ArdClient/assets/25268166/9fbd9718-ffc6-4eb0-bb85-5a31d1edc8bb)

Default client:
![image](https://github.com/Cediner/ArdClient/assets/25268166/ee579f2e-a8cb-4b96-9be6-086e100589b3)

**Comment by Cediner** [comment]
https://github.com/Cediner/ArdClient/commit/02982848ea91bd4d4e8244058ae599be5d9576a0
